FROM confluentinc/cp-kafka:7.2.1

# Adiciona os scripts de inicialização e configuração
COPY scripts/create_topics.sh /usr/bin/create_topics.sh

# Cria grupo e usuário, ajusta permissões
ARG KAFKA_GID
ARG KAFKA_UID
ARG KAFKA_USER
USER root

RUN groupadd -g ${KAFKA_GID} ${KAFKA_USER} && \
    useradd -u ${KAFKA_UID} -g ${KAFKA_GID} ${KAFKA_USER} && \
    mkdir -p /var/lib/kafka /var/log/kafka && \
    chown -R ${KAFKA_USER}:${KAFKA_USER} /var/lib/kafka /var/log/kafka && \
    chmod +x /usr/bin/create_topics.sh && \
    chown -R ${KAFKA_USER}:${KAFKA_USER} /usr/bin/create_topics.sh

# Define o usuário para o contêiner
USER ${KAFKA_USER}

ENTRYPOINT ["/usr/bin/create_topics.sh"]
