FROM confluentinc/cp-zookeeper:7.2.1

# Cria grupo e usuário, ajusta permissões
ARG ZOOKEEPER_GID
ARG ZOOKEEPER_UID
ARG ZOOKEEPER_USER
USER root

RUN groupadd -g ${ZOOKEEPER_GID} ${ZOOKEEPER_USER} && \
    useradd -u ${ZOOKEEPER_UID} -g ${ZOOKEEPER_GID} ${ZOOKEEPER_USER} && \
    mkdir -p /var/lib/zookeeper /var/log/zookeeper && \
    chown -R ${ZOOKEEPER_USER}:${ZOOKEEPER_USER} /var/lib/zookeeper /var/log/zookeeper  && \
    mkdir -p /etc/kafka/ && \
    chmod -R 777 /etc/kafka/  && \
    mkdir -p /var/log/kafka/  && \
    chown -R ${ZOOKEEPER_USER}:${ZOOKEEPER_USER} /var/log/kafka/  && \
    chmod -R 755 /var/log/kafka/
# Define o usuário para o contêiner
USER ${ZOOKEEPER_USER}

CMD ["/etc/confluent/docker/run"]
FROM zookeeper:latest
