version: '3.8'

x-common-zookeeper-setup: &common-zookeeper-setup
  image: confluentinc/cp-zookeeper:${ZOOKEEPER_VERSION}
  user: ${ZOOKEEPER_UID}:${ZOOKEEPER_GID}
  environment:
    ZOOKEEPER_CLIENT_PORT: ${ZOOKEEPER_CLIENT_PORT}
    ZOOKEEPER_TICK_TIME: ${ZOOKEEPER_TICK_TIME}
    ZOOKEEPER_INIT_LIMIT: ${ZOOKEEPER_INIT_LIMIT}
    ZOOKEEPER_SYNC_LIMIT: ${ZOOKEEPER_SYNC_LIMIT}
    ZOOKEEPER_AUTOPURGE_SNAP_RETAIN_COUNT: ${ZOOKEEPER_AUTOPURGE_SNAP_RETAIN_COUNT}
    ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL: ${ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL}
    ZOOKEEPER_SERVERS: ${ZOOKEEPER_SERVERS}
  volumes:
    - zookeeper_data:/var/lib/zookeeper
  networks:
    - kafka_network
  command:
    - bash
    - -c
    - |
      groupadd -g ${ZOOKEEPER_GID} ${ZOOKEEPER_USER} && \
      useradd -u ${ZOOKEEPER_UID} -g ${ZOOKEEPER_GID} ${ZOOKEEPER_USER} && \
      chown -R ${ZOOKEEPER_USER}:${ZOOKEEPER_USER} /var/lib/zookeeper && \
      chown -R ${ZOOKEEPER_USER}:${ZOOKEEPER_USER} /var/log/zookeeper && \
      exec gosu ${ZOOKEEPER_USER} /etc/confluent/docker/run

x-common-kafka-setup: &common-kafka-setup
  image: confluentinc/cp-kafka:${KAFKA_VERSION}
  user: ${KAFKA_UID}:${KAFKA_GID}
  depends_on:
    - zookeeper1
    - zookeeper2
    - zookeeper3
  environment:
    KAFKA_ZOOKEEPER_CONNECT: ${ZOOKEEPER_SERVERS}
    KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: ${KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR}
    KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: ${KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR}
    KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: ${KAFKA_TRANSACTION_STATE_LOG_MIN_ISR}
    KAFKA_LOG_RETENTION_HOURS: ${KAFKA_LOG_RETENTION_HOURS}
    KAFKA_LOG_RETENTION_BYTES: ${KAFKA_LOG_RETENTION_BYTES}
    KAFKA_LOG_SEGMENT_BYTES: ${KAFKA_LOG_SEGMENT_BYTES}
    KAFKA_NUM_PARTITIONS: ${KAFKA_NUM_PARTITIONS}
  volumes:
    - kafka_data:/var/lib/kafka
    - ./scripts/create_topics.sh:/usr/bin/create_topics.sh
  networks:
    - kafka_network
  command:
    - bash
    - -c
    - |
      groupadd -g ${KAFKA_GID} ${KAFKA_USER} && \
      useradd -u ${KAFKA_UID} -g ${KAFKA_GID} ${KAFKA_USER} && \
      chown -R ${KAFKA_USER}:${KAFKA_USER} /var/lib/kafka && \
      chown -R ${KAFKA_USER}:${KAFKA_USER} /var/log/kafka && \
      /etc/confluent/docker/run & \
      /usr/bin/create_topics.sh

services:
  zookeeper1:
    <<: *common-zookeeper-setup
    environment:
      ZOOKEEPER_SERVER_ID: 1

  zookeeper2:
    <<: *common-zookeeper-setup
    environment:
      ZOOKEEPER_SERVER_ID: 2

  zookeeper3:
    <<: *common-zookeeper-setup
    environment:
      ZOOKEEPER_SERVER_ID: 3

  kafka1:
    <<: *common-kafka-setup
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092

  kafka2:
    <<: *common-kafka-setup
    ports:
      - 9093:9092
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9093

  kafka3:
    <<: *common-kafka-setup
    ports:
      - 9094:9092
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:9094

volumes:
  kafka_data:
  zookeeper_data:

networks:
  kafka_network:
    driver: bridge
