version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:${ZOOKEEPER_VERSION}
    user: ${ZOOKEEPER_UID}:${ZOOKEEPER_GID}
    environment:
      ZOOKEEPER_CLIENT_PORT: ${ZOOKEEPER_CLIENT_PORT}
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
    command:
      - bash
      - -c
      - |
        groupadd -g ${ZOOKEEPER_GID} ${ZOOKEEPER_USER} && \
        useradd -u ${ZOOKEEPER_UID} -g ${ZOOKEEPER_GID} ${ZOOKEEPER_USER} && \
        chown -R ${ZOOKEEPER_USER}:${ZOOKEEPER_USER} /var/lib/zookeeper && \
        chown -R ${ZOOKEEPER_USER}:${ZOOKEEPER_USER} /var/log/zookeeper && \
        exec gosu ${ZOOKEEPER_USER} /etc/confluent/docker/run

  kafka:
    image: confluentinc/cp-kafka:${KAFKA_VERSION}
    user: ${KAFKA_UID}:${KAFKA_GID}
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: ${KAFKA_BROKER_ID}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:${ZOOKEEPER_CLIENT_PORT}
      KAFKA_ADVERTISED_LISTENERS: ${KAFKA_ADVERTISED_LISTENERS}
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: ${KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR}
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: ${KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR}
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: ${KAFKA_TRANSACTION_STATE_LOG_MIN_ISR}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - bash
      - -c
      - |
        groupadd -g ${KAFKA_GID} ${KAFKA_USER} && \
        useradd -u ${KAFKA_UID} -g ${KAFKA_GID} ${KAFKA_USER} && \
        chown -R ${KAFKA_USER}:${KAFKA_USER} /var/lib/kafka && \
        chown -R ${KAFKA_USER}:${KAFKA_USER} /var/log/kafka && \
        exec gosu ${KAFKA_USER} /etc/confluent/docker/run
