# docker-compose.yml
services:
  zookeeper1:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: kafka
    container_name: kafkaZookeeper
    networks:
      - kafka_network    
    ports:
      - 2181:2181
      - 9092:9092
    healthcheck:
      test: ["CMD", "echo", "ruok", "|", "nc", "localhost", "2181"]
      interval: 10s
      timeout: 5s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
networks:
  kafka_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.2.0/24
          gateway: 192.168.2.1
